language: python

sudo: required
dist: trusty
python:
  - '2.7'

os:
    linux

install:
  - pip install -e . --use-mirrors

before_script:
  - pip install -r test_requirements.txt --use-mirrors
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
  - py.test example/tests.py --cov=example
  - cd -

script:
  - py.test application/my_app.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
